#ifndef AUV_HARDWARE_PRESET_H
#define AUV_HARDWARE_PRESET_H

/*
 * One compile-time choice assembles the complete depth-sensor/pushrod pair.
 * Keep this header C-compatible: CubeMX HAL sources use it too.
 */
#define AUV_HARDWARE_PRESET_SELF_CALC_BOARD 1
#define AUV_HARDWARE_PRESET_SELF_DEPTH_GPIO_PUSHROD 2
#define AUV_HARDWARE_PRESET_COMMERCIAL_DEPTH 3
#define AUV_HARDWARE_PRESET_M14_DEPTH 4
#define AUV_HARDWARE_PRESET_I2C_DEPTH 5
#define AUV_HARDWARE_PRESET_COMMERCIAL_GPIO_PUSHROD 6
#define AUV_HARDWARE_PRESET_M14_GPIO_PUSHROD 7

#ifndef AUV_HARDWARE_PRESET
#define AUV_HARDWARE_PRESET AUV_HARDWARE_PRESET_SELF_CALC_BOARD
#endif

/* Derived values are implementation details of the selected preset. */
#if AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_SELF_CALC_BOARD
#define AUV_PRESET_DEPTH_BACKEND 2
#define AUV_PRESET_PUSHROD_BACKEND 1
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_SELF_DEPTH_GPIO_PUSHROD
#define AUV_PRESET_DEPTH_BACKEND 2
#define AUV_PRESET_PUSHROD_BACKEND 2
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_COMMERCIAL_DEPTH
#define AUV_PRESET_DEPTH_BACKEND 1
#define AUV_PRESET_PUSHROD_BACKEND 1
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_M14_DEPTH
#define AUV_PRESET_DEPTH_BACKEND 4
#define AUV_PRESET_PUSHROD_BACKEND 1
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_I2C_DEPTH
#define AUV_PRESET_DEPTH_BACKEND 3
#define AUV_PRESET_PUSHROD_BACKEND 1
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_COMMERCIAL_GPIO_PUSHROD
#define AUV_PRESET_DEPTH_BACKEND 1
#define AUV_PRESET_PUSHROD_BACKEND 2
#elif AUV_HARDWARE_PRESET == AUV_HARDWARE_PRESET_M14_GPIO_PUSHROD
#define AUV_PRESET_DEPTH_BACKEND 4
#define AUV_PRESET_PUSHROD_BACKEND 2
#else
#error "Unsupported AUV_HARDWARE_PRESET value"
#endif

/* Compatibility names used internally by existing backend source files. */
#define DEPTH_BACKEND_COMMERCIAL_UART 1
#define DEPTH_BACKEND_SELF_UART 2
#define DEPTH_BACKEND_I2C 3
#define DEPTH_BACKEND_M14_UART 4
#define PUSHROD_BACKEND_SELF_UART 1
#define PUSHROD_BACKEND_GPIO 2

#ifdef DEPTH_SENSOR_BACKEND
#undef DEPTH_SENSOR_BACKEND
#endif
#ifdef PUSHROD_BACKEND
#undef PUSHROD_BACKEND
#endif
#define DEPTH_SENSOR_BACKEND AUV_PRESET_DEPTH_BACKEND
#define PUSHROD_BACKEND AUV_PRESET_PUSHROD_BACKEND

#if AUV_PRESET_PUSHROD_BACKEND == PUSHROD_BACKEND_GPIO
#define AUV_PRESET_USES_GPIO_PUSHROD 1
#else
#define AUV_PRESET_USES_GPIO_PUSHROD 0
#endif

#if AUV_PRESET_DEPTH_BACKEND == DEPTH_BACKEND_I2C
#define AUV_PRESET_USES_I2C_DEPTH 1
#else
#define AUV_PRESET_USES_I2C_DEPTH 0
#endif

#endif /* AUV_HARDWARE_PRESET_H */
